import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Tables, TablesInsert } from "@/integrations/supabase/types";
import { QK } from "@/lib/queryKeys";
import { useMyCouple } from "@/hooks/useCouple";
import { User } from "@supabase/supabase-js";

export type Profile = Tables<"profiles">;

function getPreferredDisplayName(user: User): string {
  return (
    user.user_metadata?.display_name ||
    user.user_metadata?.full_name ||
    user.user_metadata?.name ||
    user.email?.split("@")[0] ||
    "User"
  );
}

function getPreferredAvatarUrl(user: User): string | null {
  return (
    user.user_metadata?.avatar_url ||
    user.user_metadata?.picture ||
    null
  );
}

function buildProfileFromUser(user: User): TablesInsert<"profiles"> {
  return {
    user_id: user.id,
    display_name: getPreferredDisplayName(user),
    avatar_url: getPreferredAvatarUrl(user),
  };
}

function shouldRefreshDisplayName(profile: Profile, user: User): boolean {
  const preferred = getPreferredDisplayName(user);
  const current = profile.display_name?.trim();
  const emailPrefix = user.email?.split("@")[0]?.trim();

  if (!preferred) return false;
  if (!current) return true;
  if (current === preferred) return false;

  // Replace the autogenerated email-prefix fallback with the richer Google name.
  if (emailPrefix && current === emailPrefix && preferred !== emailPrefix) return true;

  return false;
}

function shouldRefreshAvatar(profile: Profile, user: User): boolean {
  const preferredAvatar = getPreferredAvatarUrl(user);
  return !profile.avatar_url && !!preferredAvatar;
}

export function useProfile() {
  const { user } = useAuth();

  return useQuery({
    queryKey: QK.profile(user?.id),
    staleTime: 5 * 60_000,

    queryFn: async () => {
      if (!user) return null;

      const { data, error } = await supabase
        .from("profiles")
        .select("*")
        .eq("user_id", user.id)
        .maybeSingle();

      if (error) throw error;

      if (!data) {
        const newProfile = buildProfileFromUser(user);

        const { data: inserted, error: insertError } = await supabase
          .from("profiles")
          .insert(newProfile)
          .select()
          .single();

        if (insertError) throw insertError;

        return inserted as Profile;
      }

      const existing = data as Profile;
      const needsDisplayNameRefresh = shouldRefreshDisplayName(existing, user);
      const needsAvatarRefresh = shouldRefreshAvatar(existing, user);

      if (!needsDisplayNameRefresh && !needsAvatarRefresh) {
        return existing;
      }

      const patch: TablesInsert<"profiles"> = { user_id: user.id };
      if (needsDisplayNameRefresh) patch.display_name = getPreferredDisplayName(user);
      if (needsAvatarRefresh) patch.avatar_url = getPreferredAvatarUrl(user);

      const { data: updated, error: updateError } = await supabase
        .from("profiles")
        .upsert(patch, { onConflict: "user_id" })
        .select()
        .single();

      if (updateError) throw updateError;

      return updated as Profile;
    },

    enabled: !!user,
  });
}

export function useAllProfiles() {
  const { user } = useAuth();
  const { data: couple } = useMyCouple();

  const partnerId =
    couple?.status === "active"
      ? couple.user1_id === user?.id
        ? couple.user2_id
        : couple.user1_id
      : null;

  return useQuery({
    queryKey: [...QK.profilesAll(), partnerId],
    staleTime: 5 * 60_000,

    queryFn: async () => {
      if (!user) return [];

      const ids = [user.id];

      if (partnerId) ids.push(partnerId);

      const { data, error } = await supabase
        .from("profiles")
        .select("*")
        .in("user_id", ids);

      if (error) throw error;

      return data as Profile[];
    },

    enabled: !!user,
  });
}

export function useUpdateProfile() {
  const qc = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async ({
      displayName,
      avatarUrl,
    }: {
      displayName?: string;
      avatarUrl?: string;
    }) => {
      if (!user) throw new Error("User not authenticated");

      const payload: TablesInsert<"profiles"> = {
        user_id: user.id,
      };

      if (displayName !== undefined) {
        payload.display_name = displayName;
      }

      if (avatarUrl !== undefined) {
        payload.avatar_url = avatarUrl;
      }

      const { error } = await supabase
        .from("profiles")
        .upsert(payload, { onConflict: "user_id" });

      if (error) throw error;
    },

    onSuccess: () => {
      qc.invalidateQueries({ queryKey: QK.profile() });
      qc.invalidateQueries({ queryKey: QK.profilesAll() });
    },
  });
}

export function useUploadAvatar() {
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (file: File) => {
      if (!user) throw new Error("User not authenticated");

      const ext = file.name.split(".").pop();
      const path = `${user.id}/avatar.${ext}`;

      const { error: uploadError } = await supabase.storage
        .from("avatars")
        .upload(path, file, { upsert: true });

      if (uploadError) throw uploadError;

      const { data } = supabase.storage
        .from("avatars")
        .getPublicUrl(path);

      return data.publicUrl + `?t=${Date.now()}`;
    },
  });
}

export function useStorageUsage() {
  const { user } = useAuth();

  return useQuery({
    queryKey: QK.storageUsage(),
    staleTime: 5 * 60_000,

    queryFn: async () => {
      const { data, error } = await supabase
        .from("media")
        .select("file_size")
        .is("deleted_at", null);

      if (error) throw error;

      return (data ?? []).reduce(
        (sum, m) => sum + (m.file_size ?? 0),
        0
      );
    },

    enabled: !!user,
  });
}
